version: '3.8'

services:
  dev-db:
    image: 'postgres:${POSTGRES_VERSION}'
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: 'postgres:${POSTGRES_VERSION}'
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
